version: '3.9'

services:
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=asd
      - POSTGRES_USER=username
      - POSTGRES_DB=betbuddies_db